
# Project Site Details
site_name: OpeyemiTechPro Projects Portfolio
site_url: https://opeyemitechpro.github.io/my-projects/
site_description: A collection of DevOps and Cloud related projects

# Repo Details
repo_url: https://github.com/opeyemitechpro/my-projects
repo_name: opeyemitechpro/my-projects
edit_uri: edit/main/docs/


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.indexes
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.code.select
    - content.code.annotate
    - content.action.view
    - content.action.edit
  
    
  favicon: images/favicon.png
  logo: images/favicon.png
  language: en
  
  palette:
  
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
        
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

plugins:
  - social:
      cards_layout: default/accent
  - search
  - tags:
     tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
     tags_slugify_separator: _
     tags_slugify_format: "tag:{slug}"
     tags_hierarchy: true
  # - git-authors
  # - git-revision-date-localize:
  #    enable_creation_date: true
  #    type: iso_datetime
  - privacy  

extra:
  homepage: https://opeyemitechpro.github.io
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/opeyemitechpro
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opeyemitechpro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/opeyemi-okuboyejo/
  analytics:
    provider: google
    property: G-451838625
    feedback:
      title: Was this page helpful? Please give a feedback
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help me to improve this page by
            using my <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

# Extra StyleSheets
extra_css:
  - stylesheets/extra.css

  
# Extensions
markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - attr_list
  - abbr
  - admonition
  - def_list
  - toc:
      permalink: true
      permalink_title: Copy this link to reference this section
      title: Topics on This Page
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  

copyright: |
  &copy; 2023 - 2024 <a href="https://opeyemitechpro.github.io"  target="_blank" rel="noopener">Opeyemi Okuboyejo</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ||&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Hosted on GitHub &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ||&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  <a href="#__consent">Change cookie settings</a>

# Page Navigation
nav:
  - Start Here: index.md
   # - AWS Projects: openvpn_access_server.md
  - Terraform Projects: 
    - terraform_projects/index.md
    - terraform_projects/openvpn_access_server.md
  - DevOps Projects:
    - devops_projects/index.md
  - AWS Projects:
    - aws_projects/index.md
  - Knowledge Base:
    - kb/index.md
