
# Project Site Details
site_name: My Projects Portfolio
site_url: https://opeyemitechpro.github.io/my-projects/
site_description: A collection of DevOps and Cloud related projects

# Repo Details
repo_url: https://github.com/opeyemitechpro/my-projects
repo_name: opeyemitechpro/my-projects

# Page Navigation
 # nav:
   # - Welcome: index.md
   # - AWS Projects: openvpn_access_server.md
   # - Terraform Projects: openvpn_access_server.md
   #  - OpenVPN Access Server: openvpn_access_server.md
   # - DevOps Projects: openvpn_access_server.md
   # - CI/CD: openvpn_access_server.md
   # - Cloud Projects: openvpn_access_server.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.path
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  favicon: images/favicon.png
  logo: images/favicon.png
  language: en
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: white
    
plugins:
  - social
  - search

extra:
  homepage: https://opeyemitechpro.github.io
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/opeyemitechpro
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opeyemitechpro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/opeyemi-okuboyejo/

markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://opeyemitechpro.github.io"  target="_blank" rel="noopener">Opeyemi Okuboyejo</a>
