
# Project Site Details
site_name: My Projects Portfolio
site_url: https://opeyemitechpro.github.io/my-projects/
site_description: A collection of DevOps and Cloud related projects

# Repo Details
repo_url: https://github.com/opeyemitechpro/my-projects
repo_name: opeyemitechpro/my-projects

# Page Navigation
 # nav:
   - Home Page: index.md
   # - AWS Projects: openvpn_access_server.md
   - Terraform Projects: 
      - Terraform Projects1: 
        - terraform_projects/openvpn_access_server.md
   #  - OpenVPN Access Server: openvpn_access_server.md
   # - DevOps Projects: openvpn_access_server.md
   # - CI/CD: openvpn_access_server.md
   # - Cloud Projects: openvpn_access_server.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.code.select
    - content.code.annotate
  favicon: images/favicon.png
  logo: images/favicon.png
  language: en
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-1
        name: Switch to system preference

plugins:
  - social
  - search
  # - glightbox

extra:
  homepage: https://opeyemitechpro.github.io
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/opeyemitechpro
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opeyemitechpro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/opeyemi-okuboyejo/

markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - abbr
  - admonition
  - def_list
  - toc:
      permalink: true
      # permalink_title: Anchor link to this section for reference
      # title: On this page
      # toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences

copyright: |
  &copy; 2023 - 2024 <a href="https://opeyemitechpro.github.io"  target="_blank" rel="noopener">Opeyemi Okuboyejo</a> | Hosted on GitHub
